/*
 * generated by Xtext
 */
package textVerduler;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TextVerdulerRuntimeModule extends textVerduler.AbstractTextVerdulerRuntimeModule {

}
