/*
 * generated by Xtext
 */
package textVerduler;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TextVerdulerStandaloneSetup extends TextVerdulerStandaloneSetupGenerated{

	public static void doSetup() {
		new TextVerdulerStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

