/**
 * generated by Xtext
 */
package textVerduler.ui.contentassist;

import textVerduler.ui.contentassist.AbstractTextVerdulerProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class TextVerdulerProposalProvider extends AbstractTextVerdulerProposalProvider {
}
