/*
 * generated by Xtext
 */
package textVerduler.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import textVerduler.services.TextVerdulerGrammarAccess;

public class TextVerdulerParser extends AbstractContentAssistParser {
	
	@Inject
	private TextVerdulerGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected textVerduler.ui.contentassist.antlr.internal.InternalTextVerdulerParser createParser() {
		textVerduler.ui.contentassist.antlr.internal.InternalTextVerdulerParser result = new textVerduler.ui.contentassist.antlr.internal.InternalTextVerdulerParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getVerduleriaAccess().getAnotacionesAlternatives_0(), "rule__Verduleria__AnotacionesAlternatives_0");
					put(grammarAccess.getTotalDeCompraAccess().getUnTotalAlternatives_0_0(), "rule__TotalDeCompra__UnTotalAlternatives_0_0");
					put(grammarAccess.getProductoAccess().getAlternatives_0(), "rule__Producto__Alternatives_0");
					put(grammarAccess.getArticuloAccess().getUnArticuloAlternatives_0(), "rule__Articulo__UnArticuloAlternatives_0");
					put(grammarAccess.getUnidadAccess().getUnaUnidadAlternatives_0(), "rule__Unidad__UnaUnidadAlternatives_0");
					put(grammarAccess.getEstadoDeudaAccess().getAlternatives_0(), "rule__EstadoDeuda__Alternatives_0");
					put(grammarAccess.getModelClienteAccess().getGroup(), "rule__ModelCliente__Group__0");
					put(grammarAccess.getModelProductoAccess().getGroup(), "rule__ModelProducto__Group__0");
					put(grammarAccess.getVentaAccess().getGroup(), "rule__Venta__Group__0");
					put(grammarAccess.getVentaAccess().getGroup_2(), "rule__Venta__Group_2__0");
					put(grammarAccess.getTotalDeCompraAccess().getGroup(), "rule__TotalDeCompra__Group__0");
					put(grammarAccess.getMercaderiaAccess().getGroup(), "rule__Mercaderia__Group__0");
					put(grammarAccess.getProductoAccess().getGroup(), "rule__Producto__Group__0");
					put(grammarAccess.getValorDelProductoAccess().getGroup(), "rule__ValorDelProducto__Group__0");
					put(grammarAccess.getDescripcionAccess().getGroup(), "rule__Descripcion__Group__0");
					put(grammarAccess.getCantidadAccess().getGroup(), "rule__Cantidad__Group__0");
					put(grammarAccess.getClienteAccess().getGroup(), "rule__Cliente__Group__0");
					put(grammarAccess.getEstadoDeudaAccess().getGroup(), "rule__EstadoDeuda__Group__0");
					put(grammarAccess.getImporteAccess().getGroup(), "rule__Importe__Group__0");
					put(grammarAccess.getVerduleriaAccess().getAnotacionesAssignment(), "rule__Verduleria__AnotacionesAssignment");
					put(grammarAccess.getModelClienteAccess().getClientesAssignment_0(), "rule__ModelCliente__ClientesAssignment_0");
					put(grammarAccess.getModelClienteAccess().getEstadoDeDeudaAssignment_2(), "rule__ModelCliente__EstadoDeDeudaAssignment_2");
					put(grammarAccess.getModelProductoAccess().getProductosAssignment_0(), "rule__ModelProducto__ProductosAssignment_0");
					put(grammarAccess.getModelProductoAccess().getValorAssignment_1(), "rule__ModelProducto__ValorAssignment_1");
					put(grammarAccess.getModelVentaAccess().getVentaAssignment(), "rule__ModelVenta__VentaAssignment");
					put(grammarAccess.getVentaAccess().getNombreAssignment_0(), "rule__Venta__NombreAssignment_0");
					put(grammarAccess.getVentaAccess().getUnaListaDeComprasAssignment_2_0(), "rule__Venta__UnaListaDeComprasAssignment_2_0");
					put(grammarAccess.getVentaAccess().getUnImporteAssignment_4(), "rule__Venta__UnImporteAssignment_4");
					put(grammarAccess.getVentaAccess().getUnTotalAssignment_6(), "rule__Venta__UnTotalAssignment_6");
					put(grammarAccess.getTotalDeCompraAccess().getUnTotalAssignment_0(), "rule__TotalDeCompra__UnTotalAssignment_0");
					put(grammarAccess.getTotalDeCompraAccess().getUnImporteTotalAssignment_1(), "rule__TotalDeCompra__UnImporteTotalAssignment_1");
					put(grammarAccess.getMercaderiaAccess().getUnaDescripcionAssignment_0(), "rule__Mercaderia__UnaDescripcionAssignment_0");
					put(grammarAccess.getMercaderiaAccess().getNombreDeProductoAssignment_2(), "rule__Mercaderia__NombreDeProductoAssignment_2");
					put(grammarAccess.getProductoAccess().getNombreDeProductoAssignment_1(), "rule__Producto__NombreDeProductoAssignment_1");
					put(grammarAccess.getValorDelProductoAccess().getUnaDescripcionAssignment_1(), "rule__ValorDelProducto__UnaDescripcionAssignment_1");
					put(grammarAccess.getDescripcionAccess().getUnImporteAssignment_0(), "rule__Descripcion__UnImporteAssignment_0");
					put(grammarAccess.getDescripcionAccess().getUnaCantidadAssignment_1(), "rule__Descripcion__UnaCantidadAssignment_1");
					put(grammarAccess.getCantidadAccess().getUnArticuloAssignment_0(), "rule__Cantidad__UnArticuloAssignment_0");
					put(grammarAccess.getCantidadAccess().getUnValorAssignment_1(), "rule__Cantidad__UnValorAssignment_1");
					put(grammarAccess.getCantidadAccess().getUnaCantidadAssignment_2(), "rule__Cantidad__UnaCantidadAssignment_2");
					put(grammarAccess.getArticuloAccess().getUnArticuloAssignment(), "rule__Articulo__UnArticuloAssignment");
					put(grammarAccess.getUnidadAccess().getUnaUnidadAssignment(), "rule__Unidad__UnaUnidadAssignment");
					put(grammarAccess.getClienteAccess().getNameAssignment_1(), "rule__Cliente__NameAssignment_1");
					put(grammarAccess.getImporteAccess().getValorAssignment_0(), "rule__Importe__ValorAssignment_0");
					put(grammarAccess.getImporteAccess().getMonedaAssignment_1(), "rule__Importe__MonedaAssignment_1");
					put(grammarAccess.getMonedaAccess().getPesosAssignment(), "rule__Moneda__PesosAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			textVerduler.ui.contentassist.antlr.internal.InternalTextVerdulerParser typedParser = (textVerduler.ui.contentassist.antlr.internal.InternalTextVerdulerParser) parser;
			typedParser.entryRuleVerduleria();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public TextVerdulerGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TextVerdulerGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
