/**
 * generated by Xtext
 */
package textVerduler.validation;

import textVerduler.validation.AbstractTextVerdulerValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class TextVerdulerValidator extends AbstractTextVerdulerValidator {
}
