/*
 * generated by Xtext
 */
package textVerduler.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import textVerduler.services.TextVerdulerGrammarAccess;

public class TextVerdulerParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TextVerdulerGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected textVerduler.parser.antlr.internal.InternalTextVerdulerParser createParser(XtextTokenStream stream) {
		return new textVerduler.parser.antlr.internal.InternalTextVerdulerParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Verduleria";
	}
	
	public TextVerdulerGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TextVerdulerGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
