/*
 * generated by Xtext
 */
package textVerduler.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import textVerduler.ui.internal.TextVerdulerActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TextVerdulerExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TextVerdulerActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TextVerdulerActivator.getInstance().getInjector(TextVerdulerActivator.TEXTVERDULER_TEXTVERDULER);
	}
	
}
