/*
 * generated by Xtext
 */
package textVerduler;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class TextVerdulerUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return textVerduler.ui.internal.TextVerdulerActivator.getInstance().getInjector("textVerduler.TextVerduler");
	}
	
}
