/*
 * generated by Xtext
 */
package textVerduler.validation

import org.eclipse.xtext.validation.Check
import textVerduler.textVerduler.Verduleria
import static extension model.VerduleriaExtensions.*
import java.util.List
import textVerduler.textVerduler.TextVerdulerPackage

//import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class TextVerdulerValidator extends AbstractTextVerdulerValidator {

	@Check
	def checkClienteNoExiste(Verduleria verduleria) {
		val List<String> nombres = newArrayList()
		verduleria.clientes.forEach [ cliente | 
			if (nombres.contains(cliente.name))
				// error
				error("El cliente ya existe", 
					cliente, 
					cliente.eClass.getEStructuralFeature(
						TextVerdulerPackage.CLIENTE__NAME
					)
				)
			else
				nombres.add(cliente.name)
		]
	}
	
	@Check
	def checkProductoNoExiste(Verduleria verduleria) {
		val List<String> nombres = newArrayList()
		verduleria.productos.forEach [ producto | 
			if (nombres.contains(producto.name))
				// error
				error("El producto ya existe", 
					producto, 
					producto.eClass.getEStructuralFeature(
						TextVerdulerPackage.PRODUCTO__NAME
					)
				)
			else
				nombres.add(producto.name)
		]
	}
}
