/*
 * generated by Xtext
 */
package textVerduler.validation

import org.eclipse.xtext.validation.Check
import textVerduler.textVerduler.Verduleria
import static extension model.VerduleriaExtensions.*
import java.util.List
import textVerduler.textVerduler.TextVerdulerPackage
import textVerduler.textVerduler.Producto
import textVerduler.textVerduler.ModelProducto

//import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class TextVerdulerValidator extends AbstractTextVerdulerValidator {

	@Check
	def checkClienteNoExiste(Verduleria verduleria) {
		val List<String> nombres = newArrayList()
		verduleria.clientes.forEach [ cliente | 
			if (nombres.contains(cliente.name))
				error("El cliente ya existe", 
					cliente, 
					cliente.eClass.getEStructuralFeature(
						TextVerdulerPackage.CLIENTE__NAME
					)
				)
			else
				nombres.add(cliente.name)
		]
	}
	
	@Check
	def checkProductoNoExiste(Verduleria verduleria) {
		val List<String> nombres = newArrayList()
		verduleria.productos.forEach [ producto | 
			if (nombres.contains(producto.name))
				error("El producto ya existe", 
					producto, 
					producto.eClass.getEStructuralFeature(
						TextVerdulerPackage.PRODUCTO__NAME
					)
				)
			else
				nombres.add(producto.name)
		]
	}
	
	@Check
	def checkPrecioPorKilo(ModelProducto producto) {
		if(producto.valor.descripcion.importe.valor > 200 && producto.valor.descripcion.cantidad.unidad == "kilo")
			error("El producto no puede valer mas de 200 pesos el kilo", 
				producto, 
				producto.eClass.getEStructuralFeature(
					TextVerdulerPackage.VALOR_DEL_PRODUCTO__DESCRIPCION
				)
			)
		
	}
}
