/*
 * generated by Xtext
 */
package textVerduler.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TextVerdulerUiModule extends textVerduler.ui.AbstractTextVerdulerUiModule {
	public TextVerdulerUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
